apiVersion : apps/v1
kind: Deployment
metadata:
  name: featurebranchapp 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: featurebranchapp
  template:
    metadata:
      labels:
        app: featurebranchapp 
    spec:
      containers:
        - name: featurebranchapp 
          image: mydockcontainer.azurecr.io/samplewebapp
          ports:
          - containerPort: 80
